export const LOAD_MEAL = 'LOAD_MEAL'
export const LOAD_MEAL_SUCCESS = 'LOAD_MEAL_SUCCESS'
export const LOAD_MEAL_FAILURE = 'LOAD_MEAL_FAILURE'

export const ADD_MEAL = 'ADD_MEAL'
export const ADD_MEAL_SUCCESS = 'ADD_MEAL_SUCCESS'
export const ADD_MEAL_FAILURE = 'ADD_MEAL_FAILURE'

export const EDIT_MEAL = 'EDIT_MEAL'
export const EDIT_MEAL_SUCCESS = 'EDIT_MEAL_SUCCESS'
export const EDIT_MEAL_FAILURE = 'EDIT_MEAL_FAILURE'
